version: '3.9'

services:
  database:
    image: postgres:13
    container_name: postgres_mono
    restart: always
    networks:
      - servers
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: explorer-v1
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: bind
        source: explorer-v1-init-data.sql
        target: /tmp/explorer-v1-init.sql
    ports:
      - "4002:5432"

  encounters_database:
    image: postgres
    container_name: postgres_encounters
    restart: always
    networks:
      - servers
    ports:
      - 4001:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: encounters
    volumes:
      - encounters_database_data:/var/lib/postgresql/data

  tours_database:
    image: postgres
    container_name: postgres_tours
    restart: always
    networks:
      - servers
    ports:
      - 4000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: tours
    volumes:
      - tours_database_data:/var/lib/postgresql/data

  explorer:
    build:
      dockerfile: Dockerfile
      context: .
      target: final
    restart: on-failure
    networks:
      - servers
    ports:
      - "44333:44333"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer-v1
    depends_on:
      - database

  tours_server:
    build:
      context: ../../tours/WebServerWithDB
      dockerfile: Dockerfile
    image: tours_server
    container_name: tours_container
    restart: always
    networks:
      - servers
    ports:
      - 8081:8081
    depends_on:
      - tours_database

  
  
  encounters_server:
    build:
      context: ../../encounters/WebServerWithDB
      dockerfile: Dockerfile
    image: encounters_server
    container_name: encounters_container
    restart: always
    networks:
      - servers
    ports:
      - 8082:8082
    depends_on:
      - encounters_database


volumes:
  database-data:
    name: explorer

  tours_database_data:
    name: tours_database_volume

  encounters_database_data:
    name: encounters_database_volume

networks:
  servers:
    name: servers
    driver: bridge
